# Create fixed Ansible playbook
cat <<EOT > playbook.yml
---
- name: Deploy Nginx Container
  hosts: localhost
  become: true
  tasks:
    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull Nginx image
      community.docker.docker_image:
        name: nginx
        source: pull
        force_source: yes

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx_server
        image: nginx
        state: started
        restart_policy: unless-stopped
        ports:
          - "80:80"
        log_driver: json-file
        log_options:
          max-size: "10m"
          max-file: "3"
EOT

# Run with debug
ANSIBLE_DEBUG=1 ansible-playbook playbook.yml
